### ISSUE TITLE
问题

### ISSUE THREAD

**Issue by pengkaii** [hhz0328/ros_exoskeleton_maxon_simulation#1]
您好，请问这个是哪个课呀，有基于点云图 进行机械臂轨迹规划的资料吗

**Comment by hhz0328** [comment]
看官方手册moveit+ros-control即可












胡翰泽
***@***.***

15158376514

---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年1月20日(周六) 下午4:19
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [hhz0328/ros1_exoskeleton_maxon_simulation] 问题 (Issue #1)




 
您好，请问这个是哪个课呀，有基于点云图 进行机械臂轨迹规划的资料吗
